### ISSUE TITLE
Error with IBM Java based images

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/ci.docker#218]
Encountered the following issue when trying to run Open Liberty images built on IBM Java:

```
> docker run openliberty/open-liberty:full-java8-ibmjava-ubi

JVMSHRC561E Failed to initialize the shared classes cache, there is not enough space in the file system. Available free disk space bytes = 0, requested bytes = 49283072.
JVMSHRC840E Failed to start up the shared cache.
JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified
CWWKE0005E: The runtime environment could not be launched.
CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.IllegalStateException: The state  could not be created. state=/opt/ol/wlp/output/defaultServer/logs/state
com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.IllegalStateException: The state  could not be created. state=/opt/ol/wlp/output/defaultServer/logs/state
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:732)
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:220)
	at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:241)
	at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:117)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
Caused by: java.lang.IllegalStateException: The state  could not be created. state=/opt/ol/wlp/output/defaultServer/logs/state
	at com.ibm.ws.kernel.boot.internal.KernelUtils.cleanDirectory(KernelUtils.java:208)
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.clearServerStateDir(KernelBootstrap.java:235)
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:108)
	... 4 more
```

**Comment by leochr** [comment]
@ymanton @mpirvu I believe there was a similar issue with OpenJDK last month and was addressed. Is this a similar/known issue with IBM Java?

**Comment by mpirvu** [comment]
The message looks different. Are you sure that there is indeed free space on that machine.
I'll test it on my end as well

**Comment by leochr** [comment]
@mpirvu Tried on a different machine and didn't encounter the error. The server started fine. Cleared the images and tried on the failing machine and don't see the issue anymore. Sorry for the false alarm. Thank you.
